#!/usr/bin/python3

def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

def find_prime_factors(n):
    prime_factors = []
    if n <= 1:
        return prime_factors

    for i in range(2, n + 1):
        while is_prime(i) and n % i == 0:
            prime_factors.append(i)
            n //= i
        if n == 1:
            break

    return prime_factors

if __name__ == "__main__":
    try:
        n = int(input("Enter a number to factorize: "))
        factors = find_prime_factors(n)
        if len(factors) > 1:
            p = factors[0]
            q = n // p
            print(f"{n} = {p} * {q}")
        else:
            print(f"{n} is a prime number.")
    except ValueError:
        print("Invalid input. Please enter a valid number.")

